#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MvvX.Plugins.IOAuthClient.Droid.Resource", IsApplication=false)]

namespace MvvX.Plugins.IOAuthClient.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public static int slide_in_right = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int slide_out_left = 2130771969;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public static int font = 2130837504;
			
			// aapt resource value: 0x7F020001
			public static int fontProviderAuthority = 2130837505;
			
			// aapt resource value: 0x7F020002
			public static int fontProviderCerts = 2130837506;
			
			// aapt resource value: 0x7F020003
			public static int fontProviderFetchStrategy = 2130837507;
			
			// aapt resource value: 0x7F020004
			public static int fontProviderFetchTimeout = 2130837508;
			
			// aapt resource value: 0x7F020005
			public static int fontProviderPackage = 2130837509;
			
			// aapt resource value: 0x7F020006
			public static int fontProviderQuery = 2130837510;
			
			// aapt resource value: 0x7F020007
			public static int fontStyle = 2130837511;
			
			// aapt resource value: 0x7F020008
			public static int fontWeight = 2130837512;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F030000
			public static int abc_action_bar_embed_tabs = 2130903040;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F040000
			public static int notification_action_color_filter = 2130968576;
			
			// aapt resource value: 0x7F040001
			public static int notification_icon_bg_color = 2130968577;
			
			// aapt resource value: 0x7F040002
			public static int ripple_material_light = 2130968578;
			
			// aapt resource value: 0x7F040003
			public static int secondary_text_default_material_light = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F050000
			public static int compat_button_inset_horizontal_material = 2131034112;
			
			// aapt resource value: 0x7F050001
			public static int compat_button_inset_vertical_material = 2131034113;
			
			// aapt resource value: 0x7F050002
			public static int compat_button_padding_horizontal_material = 2131034114;
			
			// aapt resource value: 0x7F050003
			public static int compat_button_padding_vertical_material = 2131034115;
			
			// aapt resource value: 0x7F050004
			public static int compat_control_corner_material = 2131034116;
			
			// aapt resource value: 0x7F050005
			public static int notification_action_icon_size = 2131034117;
			
			// aapt resource value: 0x7F050006
			public static int notification_action_text_size = 2131034118;
			
			// aapt resource value: 0x7F050007
			public static int notification_big_circle_margin = 2131034119;
			
			// aapt resource value: 0x7F050008
			public static int notification_content_margin_start = 2131034120;
			
			// aapt resource value: 0x7F050009
			public static int notification_large_icon_height = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public static int notification_large_icon_width = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public static int notification_main_column_padding_top = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public static int notification_media_narrow_margin = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public static int notification_right_icon_size = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public static int notification_right_side_padding_top = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public static int notification_small_icon_background_padding = 2131034127;
			
			// aapt resource value: 0x7F050010
			public static int notification_small_icon_size_as_large = 2131034128;
			
			// aapt resource value: 0x7F050011
			public static int notification_subtext_size = 2131034129;
			
			// aapt resource value: 0x7F050012
			public static int notification_top_pad = 2131034130;
			
			// aapt resource value: 0x7F050013
			public static int notification_top_pad_large_text = 2131034131;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F060000
			public static int ic_arrow_back = 2131099648;
			
			// aapt resource value: 0x7F060001
			public static int notification_action_background = 2131099649;
			
			// aapt resource value: 0x7F060002
			public static int notification_bg = 2131099650;
			
			// aapt resource value: 0x7F060003
			public static int notification_bg_low = 2131099651;
			
			// aapt resource value: 0x7F060004
			public static int notification_bg_low_normal = 2131099652;
			
			// aapt resource value: 0x7F060005
			public static int notification_bg_low_pressed = 2131099653;
			
			// aapt resource value: 0x7F060006
			public static int notification_bg_normal = 2131099654;
			
			// aapt resource value: 0x7F060007
			public static int notification_bg_normal_pressed = 2131099655;
			
			// aapt resource value: 0x7F060008
			public static int notification_icon_background = 2131099656;
			
			// aapt resource value: 0x7F060009
			public static int notification_template_icon_bg = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public static int notification_template_icon_low_bg = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public static int notification_tile_bg = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public static int notify_panel_notification_icon_bg = 2131099660;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F070004
			public static int actions = 2131165188;
			
			// aapt resource value: 0x7F070000
			public static int action_container = 2131165184;
			
			// aapt resource value: 0x7F070001
			public static int action_divider = 2131165185;
			
			// aapt resource value: 0x7F070002
			public static int action_image = 2131165186;
			
			// aapt resource value: 0x7F070003
			public static int action_text = 2131165187;
			
			// aapt resource value: 0x7F070005
			public static int async = 2131165189;
			
			// aapt resource value: 0x7F070006
			public static int blocking = 2131165190;
			
			// aapt resource value: 0x7F070007
			public static int chronometer = 2131165191;
			
			// aapt resource value: 0x7F070008
			public static int forever = 2131165192;
			
			// aapt resource value: 0x7F070009
			public static int icon = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public static int icon_group = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public static int info = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public static int italic = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public static int line1 = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public static int line3 = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public static int normal = 2131165199;
			
			// aapt resource value: 0x7F070010
			public static int notification_background = 2131165200;
			
			// aapt resource value: 0x7F070011
			public static int notification_main_column = 2131165201;
			
			// aapt resource value: 0x7F070012
			public static int notification_main_column_container = 2131165202;
			
			// aapt resource value: 0x7F070013
			public static int right_icon = 2131165203;
			
			// aapt resource value: 0x7F070014
			public static int right_side = 2131165204;
			
			// aapt resource value: 0x7F070015
			public static int text = 2131165205;
			
			// aapt resource value: 0x7F070016
			public static int text2 = 2131165206;
			
			// aapt resource value: 0x7F070017
			public static int time = 2131165207;
			
			// aapt resource value: 0x7F070018
			public static int title = 2131165208;
			
			// aapt resource value: 0x7F070019
			public static int webview = 2131165209;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F080000
			public static int status_bar_notification_info_maxnum = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F090000
			public static int activity_webview = 2131296256;
			
			// aapt resource value: 0x7F090001
			public static int notification_action = 2131296257;
			
			// aapt resource value: 0x7F090002
			public static int notification_action_tombstone = 2131296258;
			
			// aapt resource value: 0x7F090003
			public static int notification_template_custom_big = 2131296259;
			
			// aapt resource value: 0x7F090004
			public static int notification_template_icon_group = 2131296260;
			
			// aapt resource value: 0x7F090005
			public static int notification_template_part_chronometer = 2131296261;
			
			// aapt resource value: 0x7F090006
			public static int notification_template_part_time = 2131296262;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0A0000
			public static int ApplicationName = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public static int Hello = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public static int status_bar_notification_info_overflow = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public static int title_activity_webview = 2131361795;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0B0000
			public static int TextAppearance_Compat_Notification = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public static int TextAppearance_Compat_Notification_Info = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public static int TextAppearance_Compat_Notification_Line2 = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public static int TextAppearance_Compat_Notification_Time = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public static int TextAppearance_Compat_Notification_Title = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public static int Widget_Compat_NotificationActionContainer = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public static int Widget_Compat_NotificationActionText = 2131427334;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F020001,0x7F020002,0x7F020003,0x7F020004,0x7F020005,0x7F020006 }
			public static int[] FontFamily = new int[] {
					2130837505,
					2130837506,
					2130837507,
					2130837508,
					2130837509,
					2130837510};
			
			// aapt resource value: { 0x7F020000,0x7F020007,0x7F020008 }
			public static int[] FontFamilyFont = new int[] {
					2130837504,
					2130837511,
					2130837512};
			
			// aapt resource value: 0
			public static int FontFamilyFont_font = 0;
			
			// aapt resource value: 1
			public static int FontFamilyFont_fontStyle = 1;
			
			// aapt resource value: 2
			public static int FontFamilyFont_fontWeight = 2;
			
			// aapt resource value: 0
			public static int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public static int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public static int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public static int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public static int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public static int FontFamily_fontProviderQuery = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
